// <auto-generated />
using CatPhotoApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatPhotoApi.Migrations
{
    [DbContext(typeof(CatPhotoContext))]
    partial class CatPhotoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("CatPhotoApi.Models.CatPhoto", b =>
                {
                    b.Property<int>("CatPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CatPhotoId");

                    b.ToTable("CatPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
